"""Device presets and gas species data — sourced from dpf.presets + dpf.validation.experimental."""

PRESETS = {
    "pf1000": {
        "name": "PF-1000", "institution": "IPPLM Warsaw, Poland",
        "energy": "486 kJ", "class": "Large (MJ-class)",
        "voltage": 27.0, "capacitance": 1.332, "inductance_nh": 33.5, "resistance_mohm": 2.3,
        "anode_radius_mm": 80.0, "cathode_radius_mm": 160.0, "anode_length_mm": 600.0,
        "fill_gas": "D2", "fill_pressure_torr": 3.5,
        "fc_default": 0.70, "fm_default": 0.13, "sim_time_us": 10.0,
        "peak_current_exp": 1.87, "rise_time_exp": 5.8,
        "description": "One of the world's largest plasma focus machines. Located at IPPLM Warsaw, it stores 486 kJ — enough energy to heat a house for 30 seconds. Used for neutron production research and DPF physics studies.",
    },
    "pf1000_akel": {
        "name": "PF-1000 (Akel)", "institution": "IPPLM Warsaw, Poland",
        "energy": "486 kJ", "class": "Large (MJ-class)",
        "voltage": 27.0, "capacitance": 1.332, "inductance_nh": 33.5, "resistance_mohm": 8.73,
        "anode_radius_mm": 80.0, "cathode_radius_mm": 160.0, "anode_length_mm": 600.0,
        "fill_gas": "D2", "fill_pressure_torr": 3.5,
        "fc_default": 0.70, "fm_default": 0.19, "sim_time_us": 16.0,
        "peak_current_exp": 1.20, "rise_time_exp": 6.0,
        "description": "PF-1000 configured per Akel et al. (2021) 24-shot neutron yield study. Higher resistance and mass fraction reflect specific operating conditions for neutron optimization.",
    },
    "pf1000_20kv": {
        "name": "PF-1000 (20 kV)", "institution": "IPPLM Warsaw, Poland",
        "energy": "266 kJ", "class": "Large",
        "voltage": 20.0, "capacitance": 1.332, "inductance_nh": 33.5, "resistance_mohm": 2.3,
        "anode_radius_mm": 80.0, "cathode_radius_mm": 160.0, "anode_length_mm": 600.0,
        "fill_gas": "D2", "fill_pressure_torr": 3.0,
        "fc_default": 0.70, "fm_default": 0.13, "sim_time_us": 14.0,
        "peak_current_exp": 1.40, "rise_time_exp": 6.3,
        "description": "PF-1000 at reduced 20 kV charging voltage. Lower energy means slower sheath dynamics but gentler on electrodes. Used for studying voltage scaling of neutron yield.",
    },
    "nx2": {
        "name": "NX2", "institution": "NIE Singapore",
        "energy": "2.9 kJ", "class": "Compact",
        "voltage": 11.5, "capacitance": 44.0, "inductance_nh": 20.0, "resistance_mohm": 2.3,
        "anode_radius_mm": 19.0, "cathode_radius_mm": 41.0, "anode_length_mm": 50.0,
        "fill_gas": "D2", "fill_pressure_torr": 3.0,
        "fc_default": 0.70, "fm_default": 1.0, "sim_time_us": 4.0,
        "peak_current_exp": 0.40, "rise_time_exp": 1.8,
        "description": "A compact 3 kJ device at the National Institute of Education, Singapore. Small enough for a university lab, fast discharge cycle. Used for materials science and neutron imaging research.",
    },
    "unu_ictp": {
        "name": "UNU-ICTP", "institution": "United Nations University",
        "energy": "2.7 kJ", "class": "Training",
        "voltage": 14.0, "capacitance": 30.0, "inductance_nh": 110.0, "resistance_mohm": 12.0,
        "anode_radius_mm": 9.5, "cathode_radius_mm": 32.0, "anode_length_mm": 160.0,
        "fill_gas": "D2", "fill_pressure_torr": 3.0,
        "fc_default": 0.70, "fm_default": 0.08, "sim_time_us": 5.0,
        "peak_current_exp": 0.169, "rise_time_exp": 2.2,
        "description": "The UN University training device — designed to be built from locally available components in developing countries. Used in universities across 30+ countries to teach plasma physics. Small enough to fit on a lab bench.",
    },
    "poseidon": {
        "name": "POSEIDON", "institution": "Stuttgart, Germany",
        "energy": "266 kJ", "class": "Large",
        "voltage": 40.0, "capacitance": 0.333, "inductance_nh": 20.0, "resistance_mohm": 2.0,
        "anode_radius_mm": 50.0, "cathode_radius_mm": 100.0, "anode_length_mm": 400.0,
        "fill_gas": "D2", "fill_pressure_torr": 4.5,
        "fc_default": 0.65, "fm_default": 0.15, "sim_time_us": 8.0,
        "peak_current_exp": 2.60, "rise_time_exp": 5.0,
        "description": "A large device at the University of Stuttgart. Operates at 40 kV with a fast discharge, producing strong neutron yields. Used for materials testing and fusion research.",
    },
    "poseidon_60kv": {
        "name": "POSEIDON (60 kV)", "institution": "Stuttgart, Germany",
        "energy": "500 kJ", "class": "Large (high-voltage)",
        "voltage": 60.0, "capacitance": 0.277, "inductance_nh": 17.7, "resistance_mohm": 1.7,
        "anode_radius_mm": 50.0, "cathode_radius_mm": 100.0, "anode_length_mm": 400.0,
        "fill_gas": "D2", "fill_pressure_torr": 6.0,
        "fc_default": 0.45, "fm_default": 0.45, "sim_time_us": 6.0,
        "peak_current_exp": 3.19, "rise_time_exp": 1.98,
        "description": "POSEIDON at 60 kV — twice the voltage of PF-1000. Produces extremely fast sheath dynamics and the highest current (3.19 MA) of any device in our database. A benchmark for high-voltage DPF physics.",
    },
    "mjolnir": {
        "name": "MJOLNIR", "institution": "LLNL, USA",
        "energy": "1080 kJ", "class": "Very Large (MJ-class)",
        "voltage": 60.0, "capacitance": 0.600, "inductance_nh": 67.4, "resistance_mohm": 6.25,
        "anode_radius_mm": 60.0, "cathode_radius_mm": 120.0, "anode_length_mm": 500.0,
        "fill_gas": "D2", "fill_pressure_torr": 5.0,
        "fc_default": 0.70, "fm_default": 1.0, "sim_time_us": 14.0,
        "peak_current_exp": 2.80, "rise_time_exp": 5.0,
        "description": "A 1 MJ device at Lawrence Livermore National Laboratory. Named after Thor's hammer. One of the highest-energy DPF machines ever built, designed for intense neutron and X-ray production.",
    },
    "faeton": {
        "name": "FAETON-I", "institution": "Chile",
        "energy": "1100 kJ", "class": "Very Large (MJ-class)",
        "voltage": 100.0, "capacitance": 0.220, "inductance_nh": 220.0, "resistance_mohm": 7.6,
        "anode_radius_mm": 50.0, "cathode_radius_mm": 100.0, "anode_length_mm": 300.0,
        "fill_gas": "D2", "fill_pressure_torr": 12.0,
        "fc_default": 0.70, "fm_default": 0.70, "sim_time_us": 8.0,
        "peak_current_exp": 1.00, "rise_time_exp": 3.6,
        "description": "A high-voltage (100 kV) device in Chile. Uses a two-step radial fitting model (Damideh 2025). The highest voltage in our database — extreme electric fields create unique sheath dynamics.",
    },
}

GAS_SPECIES = {
    "D2": {"name": "Deuterium", "symbol": "D₂", "mass_amu": 4.028, "Z": 1,
            "description": "The standard DPF fill gas. Two deuterium nuclei can fuse to produce helium-3 + neutron (2.45 MeV) or tritium + proton (3.02 MeV). Used in most DPF fusion research."},
    "H2": {"name": "Hydrogen", "symbol": "H₂", "mass_amu": 2.016, "Z": 1,
            "description": "Lightest fill gas. No fusion neutrons (D-D threshold not met with single protons), but produces bright X-rays. Used for X-ray lithography and radiography."},
    "He": {"name": "Helium", "symbol": "He", "mass_amu": 4.003, "Z": 2,
            "description": "Noble gas — no fusion reactions but produces clean plasma for spectroscopy studies. Higher ionization energy means harder breakdown."},
    "Ne": {"name": "Neon", "symbol": "Ne", "mass_amu": 20.18, "Z": 10,
            "description": "Medium-Z noble gas. Produces soft X-rays at pinch. Heavier sheath dynamics than deuterium."},
    "Ar": {"name": "Argon", "symbol": "Ar", "mass_amu": 39.95, "Z": 18,
            "description": "Popular for X-ray production. Higher mass means slower sheath but stronger radiation at pinch. Used in material science applications."},
    "Kr": {"name": "Krypton", "symbol": "Kr", "mass_amu": 83.80, "Z": 36,
            "description": "Heavy noble gas for intense X-ray generation. Very slow sheath dynamics due to high mass."},
    "Xe": {"name": "Xenon", "symbol": "Xe", "mass_amu": 131.29, "Z": 54,
            "description": "Heaviest practical fill gas. Extreme X-ray production at pinch. Used for EUV lithography source research."},
    "N2": {"name": "Nitrogen", "symbol": "N₂", "mass_amu": 28.01, "Z": 7,
            "description": "Molecular gas. Dissociates during breakdown, adding complexity to the early discharge physics."},
}

BACKEND_LEVELS = {
    1: {"name": "Lee Model", "desc": "Circuit-only analytical model — no MHD grid. Instant results for parameter exploration and teaching.", "time": "<5 sec", "grid": "N/A", "backend": "lee"},
    2: {"name": "Python MHD", "desc": "CPU-based MHD solver using NumPy. Slower but runs on any machine without GPU. Good for learning and debugging.", "time": "~3 min", "grid": "32x64", "backend": "python"},
    3: {"name": "MLX PLM", "desc": "Apple Silicon GPU with 2nd-order PLM reconstruction and HLLS Riemann solver. Default production backend — best balance of speed and accuracy.", "time": "~1 min", "grid": "32x64", "backend": "mlx"},
    4: {"name": "MLX WENO5", "desc": "Apple Silicon GPU with 5th-order WENO-Z reconstruction. Sharper shocks and more accurate sheath dynamics. For publication-quality runs.", "time": "3-5 min", "grid": "32x64", "backend": "mlx_weno5"},
    5: {"name": "MLX Research", "desc": "Maximum fidelity: WENO5-Z + HLLD-S + SSP-RK3 + anomalous resistivity + Hall MHD on a fine 64x128 grid. For validation against experimental data.", "time": "10+ min", "grid": "64x128", "backend": "mlx_research"},
}
