"""5-angle MHD acceptance test against RADPF reference data.

This is the gate test. The MHD solver must pass ALL 5 angles against
RADPF truth data before any other work proceeds (CRITICAL_BLOCKER.md).

The 5 angles prevent specification gaming — you cannot simultaneously
fake I_peak, t_peak, waveform shape, current rise rate, AND inductance
without getting the physics right.

Truth data: tests/reference_data/radpf_pf1000_27kv.json
Generated by: Lee model with published RADPF parameters (fc=0.7, fm=0.13)
Reference: Lee & Saw, J. Fusion Energy 33:319 (2014)
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

REFERENCE_PATH = Path(__file__).parent / "reference_data" / "radpf_pf1000_27kv.json"


@pytest.fixture(scope="module")
def radpf_ref() -> dict:
    """Load RADPF reference data."""
    if not REFERENCE_PATH.exists():
        pytest.skip(f"Reference data not found: {REFERENCE_PATH}")
    with open(REFERENCE_PATH) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def mhd_result():
    """Run full MHD discharge and return result dict."""
    mlx = pytest.importorskip("mlx.core", reason="MLX not available")
    from dpf.metal.mlx_engine import run_mlx_discharge

    result = run_mlx_discharge(
        "pf1000",
        mode="mhd",
        max_steps=5000,
        grid_shape=(64, 1, 64),
    )
    return result


class TestMHDAcceptance:
    """5-angle acceptance test: MHD solver vs RADPF reference."""

    def test_angle1_ipeak(self, mhd_result, radpf_ref):
        """Angle 1: I_peak magnitude within 10% of RADPF."""
        I_mhd = abs(mhd_result["I_peak_MA"])
        I_ref = radpf_ref["scalars"]["I_peak_MA"]
        tol = radpf_ref["acceptance_criteria"]["I_peak_tolerance"]
        err = abs(I_mhd - I_ref) / I_ref
        assert err < tol, (
            f"I_peak: MHD={I_mhd:.4f} MA vs RADPF={I_ref:.4f} MA "
            f"(error={err:.1%}, tolerance={tol:.0%})"
        )

    def test_angle2_tpeak(self, mhd_result, radpf_ref):
        """Angle 2: t_peak timing within 15% of RADPF."""
        t_mhd = mhd_result["t_peak_us"]
        t_ref = radpf_ref["scalars"]["t_peak_us"]
        tol = radpf_ref["acceptance_criteria"]["t_peak_tolerance"]
        err = abs(t_mhd - t_ref) / t_ref
        assert err < tol, (
            f"t_peak: MHD={t_mhd:.2f} us vs RADPF={t_ref:.2f} us "
            f"(error={err:.1%}, tolerance={tol:.0%})"
        )

    def test_angle3_waveform_l2(self, mhd_result, radpf_ref):
        """Angle 3: I(t) waveform L2 norm within 20% of RADPF."""
        I_mhd = np.asarray(mhd_result.get("I_MA", []))
        I_ref = np.asarray(radpf_ref["time_series"]["I_kA"]) * 1e-3  # kA -> MA
        tol = radpf_ref["acceptance_criteria"]["waveform_L2_tolerance"]

        if len(I_mhd) == 0:
            pytest.skip("No I(t) waveform in MHD result")

        l2_mhd = float(np.sqrt(np.mean(I_mhd**2)))
        l2_ref = float(np.sqrt(np.mean(I_ref**2)))
        err = abs(l2_mhd - l2_ref) / max(l2_ref, 1e-30)
        assert err < tol, (
            f"Waveform L2: MHD={l2_mhd:.4f} vs RADPF={l2_ref:.4f} "
            f"(error={err:.1%}, tolerance={tol:.0%})"
        )

    def test_angle4_didt_rise(self, mhd_result, radpf_ref):
        """Angle 4: dI/dt at current rise within 25% of RADPF."""
        I_mhd = np.asarray(mhd_result.get("I_MA", []))
        t_mhd = np.asarray(mhd_result.get("t_us", []))
        tol = radpf_ref["acceptance_criteria"]["dI_dt_rise_tolerance"]

        if len(I_mhd) < 10:
            pytest.skip("Not enough MHD waveform points")

        # dI/dt at 50% of peak (current rise phase)
        idx_peak = np.argmax(np.abs(I_mhd))
        I_half = 0.5 * abs(I_mhd[idx_peak])
        idx_half = np.searchsorted(np.abs(I_mhd[:idx_peak]), I_half)

        if idx_half < 1 or idx_half >= len(t_mhd) - 1:
            pytest.skip("Cannot compute dI/dt rise from MHD waveform")

        dt = (t_mhd[idx_half] - t_mhd[idx_half - 1]) * 1e-6  # us -> s
        dI = (abs(I_mhd[idx_half]) - abs(I_mhd[idx_half - 1])) * 1e6  # MA -> A
        dI_dt_mhd = dI / max(dt, 1e-30)

        # Same computation on RADPF reference
        I_ref = np.asarray(radpf_ref["time_series"]["I_kA"]) * 1e-3  # kA -> MA
        t_ref = np.asarray(radpf_ref["time_series"]["t_us"])
        idx_peak_ref = np.argmax(np.abs(I_ref))
        I_half_ref = 0.5 * abs(I_ref[idx_peak_ref])
        idx_half_ref = np.searchsorted(np.abs(I_ref[:idx_peak_ref]), I_half_ref)

        if idx_half_ref < 1:
            pytest.skip("Cannot compute dI/dt rise from RADPF reference")

        dt_ref = (t_ref[idx_half_ref] - t_ref[idx_half_ref - 1]) * 1e-6
        dI_ref = (abs(I_ref[idx_half_ref]) - abs(I_ref[idx_half_ref - 1])) * 1e6
        dI_dt_ref = dI_ref / max(dt_ref, 1e-30)

        err = abs(dI_dt_mhd - dI_dt_ref) / max(abs(dI_dt_ref), 1e-30)
        assert err < tol, (
            f"dI/dt rise: MHD={dI_dt_mhd:.2e} A/s vs RADPF={dI_dt_ref:.2e} A/s "
            f"(error={err:.1%}, tolerance={tol:.0%})"
        )

    def test_angle5_lp_max(self, mhd_result, radpf_ref):
        """Angle 5: Peak plasma inductance within 30% of RADPF.

        This is the most sensitive angle — it directly tests whether the
        MHD density field produces correct circuit loading via L_p.
        Wider tolerance because MHD L_p depends on spatial resolution.
        """
        Lp_mhd_arr = np.asarray(mhd_result.get("Lp_mhd_nH", []))
        Lp_ref = radpf_ref["scalars"]["Lp_max_nH"]

        if len(Lp_mhd_arr) == 0:
            pytest.skip("No Lp_mhd data in MHD result")

        Lp_mhd = float(np.max(Lp_mhd_arr))
        # Use wider tolerance for Lp since it's the hardest angle
        tol = 0.30
        err = abs(Lp_mhd - Lp_ref) / max(Lp_ref, 1e-30)
        assert err < tol, (
            f"Lp_max: MHD={Lp_mhd:.2f} nH vs RADPF={Lp_ref:.2f} nH "
            f"(error={err:.1%}, tolerance={tol:.0%})"
        )
